"""followers

Revision ID: 885d0af7fa7b
Revises: ce9b5764a1f0
Create Date: 2022-03-08 08:35:05.830117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885d0af7fa7b'
down_revision = 'ce9b5764a1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
